from strands import Agent
from strands.tools import tool
import json
from src.config.config import strands_model_mini
from src.config.prompts import planner_system_prompt

@tool()
def planner_agent(query: str) -> str:
    """
    Invokes the Planner agent to get a plan for the user request.
    Args:
        user_request (str): The user's request or task description.
    Returns:
        str: The plan generated by the Planner agent as a string.
    """
    try:
        agent_planner= Agent(
            model=strands_model_mini, 
            tools=[],
            system_prompt=planner_system_prompt
        )
    except Exception as e:
        print(f"Error initializing AgentPlanner: {e}")
        agent_planner = None
    
    return str(agent_planner(query))